cardManager/urls.py
from django.urls import path, include
from cardManager import views 
# A11
from django.contrib.auth.views import LogoutView

urlpatterns = [
	path('card/<str:card_token>/', views.card_detail, name='card_view'),
	path('card/<str:card_token>/admin-register/', views.CardCreate.as_view(), name='card_create_view'),
	path('card/<str:card_token>/activate/', views.CardActivate.as_view(), name='card_activate_view'),
	path('card/<str:card_token>/fbv-update/', views.card_update, name='card_update_view'),
	path('card/<str:card_token>/class-update/', views.CardUpdate.as_view(), name='card_class_update_view'),
	path('profile/create/', views.ProfileCreate.as_view(), name='profile_create_view'),
	path('profile/slug/<str:profile_slug>/', views.ProfileDetail.as_view(), name='profile_view'),
	path('profile/slug/<str:profile_slug>/update', views.ProfileUpdate.as_view(), name='profile_update_view'),
	path('dashboard/', views.UserDashboard.as_view(), name='dashboard_view'),
	path('stats/fetch_plotly_data', views.config_plotly),
	path('api/daily_usage/', views.daily_usage, name='api_daily_usage_view'),
	path('api/daily_usage/bar_graph.png', views.daily_usage_png, name='daily_usage_graph_png_view'),
	path('order/create/', views.order_create, name='order_card_view'),
	path('order/<int:pk>/', views.OrderDetail.as_view(), name='order_detail_view'),
	# A11: CSV & JSON Exports
	path('reports/', views.Stats.as_view(), name='stats_view'),
	path('export/usage.csv', views.export_usage_csv, name='export_usage_csv_view'),
	path('export/usage.json', views.export_usage_json, name='export_usage_json_view'),
	# A11: Access Control & Authentication
	path('login/', views.CustomLoginView.as_view(), name='login_view'),
	path('logout/', LogoutView.as_view(), name='logout_view'),
	path('signup/', views.signup_view, name="signup_view"),
]

cardManager/models.py
from cardManager.utils import gen_card_token as gen_token
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.db.models import UniqueConstraint
from django.contrib.auth.models import User


class Profile(models.Model):
	profile_id = models.AutoField(primary_key=True)
	owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
	name = models.CharField(max_length=60)
	bio = models.TextField(blank=True)
	profile_slug = models.CharField(max_length=25)
	email = models.EmailField(max_length=100, blank=True)
	cell = models.CharField(max_length=12, blank=True)
	linked_in = models.URLField(max_length=200, blank=True)
	snapchat = models.CharField(max_length=50, blank=True)
	profile_photo = models.ImageField(upload_to='userPhotos/profile/', blank=True)
	banner_photo = models.ImageField(upload_to='userPhotos/banners/', blank=True)
	instagram = models.CharField(max_length=50, blank=True)
	whatsapp = models.CharField(max_length=12, blank=True)
	date_created = models.DateTimeField(default=timezone.now, editable=False)

	class Meta:
		constraints = [
			UniqueConstraint(fields=['profile_slug'], name='unique_profile_slug')
		]

	def __str__(self):
		return f"{self.profile_slug}"

	def get_absolute_url(self):
		return reverse('profile_view', kwargs={'profile_slug': self.profile_slug})
	
	def get_update_url(self):
		return reverse('profile_update_view', kwargs={'profile_slug': self.profile_slug})


class Design(models.Model):
	design_id = models.AutoField(primary_key=True)
	name = models.CharField(blank=False, null=False, max_length=50)
	front_design = models.ImageField(upload_to='cardDesigns/', blank=True)

	def __str__(self):
		return self.name


class Card(models.Model):
	card_id = models.AutoField(primary_key=True)
	token = models.CharField(max_length=20, blank=False,null=False, unique=True)
	owner = models.ForeignKey(User, on_delete=models.PROTECT, related_name='cards',null=True, blank=True, default=1)
	alias = models.CharField(max_length=60, blank=True, null=True)
	show_profile = models.BooleanField(default=False)
	reroute_url = models.URLField(max_length=200, blank=True)
	design = models.ForeignKey(Design, on_delete=models.PROTECT, related_name='cards', null=False, blank=False)

	class Meta:
		constraints = [
			UniqueConstraint(fields=['owner','alias'], name='unique_card_alias')
		]

	def __str__(self):
		return f"Card {self.token}" if self.owner else f"[Unclaimed] Card {self.token}"

	def get_absolute_url(self):
		return reverse('card_view', kwargs={'card_token': self.token})

	def get_update_url(self):
		return reverse('card_update_view', kwargs={'card_token': self.token})


class Usage(models.Model):
	card = models.ForeignKey(Card, on_delete=models.CASCADE, related_name='usage' )
	date_used = models.DateTimeField(default=timezone.now, editable=False)

	def __str__(self):
		return f'{self.date_used} {self.card}'

# A9 
class Request(models.Model):
    status_choices = [
        ('pending','Pending'),
        ('printed','Printed'),
        ('Adhered','Adhered'),
        ('complete','Complete'),
    ]
    request_id = models.AutoField(primary_key=True)
    date_created = models.DateTimeField(default=timezone.now, editable=False)
    preset_design = models.ForeignKey(Design, related_name="requests", on_delete=models.PROTECT,null=True, blank=True)
    custom_design = models.ImageField(upload_to='userPhotos/customDesigns/', blank=True)
    custom_design_rear = models.ImageField(upload_to='userPhotos/customDesigns/', blank=True)
    owner = models.ForeignKey(User, related_name="requests", on_delete=models.PROTECT, blank=False)
    card_qty = models.IntegerField(default=1)
    status = models.CharField(choices=status_choices, default='Pending', max_length=10)
    
    
    def __str__(self):
        return f"{self.owner} requested {self.card_qty} card(s)" 
    
    def get_absolute_url(self):
        return reverse("order_detail_view", kwargs={"pk": self.pk})
	

cardManager/forms.py
from django import forms
from cardManager.models import (
	Card,
	Profile,
 	Request
)
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CardForm(forms.ModelForm):
	class Meta:
		model = Card
		exclude = ['token','owner','design']

	def clean(self, **kwargs):
		data = super().clean(**kwargs)
		is_reroute_set = self.fields['reroute_url'].clean(self.data['reroute_url'])
		is_profile_set = data['show_profile']
		if is_profile_set and is_reroute_set:
			self.add_error("reroute_url","Reroute URL not needed if profile is set.")
		elif not is_profile_set and not is_reroute_set:
			self.add_error("reroute_url","Reroute URL needed.")

		return data

class AdminCardForm(forms.ModelForm):
	class Meta:
		model = Card
		fields = ['token','owner','design']

	def clean_token(self, **kwargs):
		token = self.cleaned_data.get('token')
		if token:
			return token.strip()
		return token


class ProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = '__all__'
  

class RequestForm(forms.ModelForm):
	class Meta:
		model = Request
		fields = ['preset_design','custom_design', 'custom_design_rear', 'card_qty']

# =====================================================================================================
# A11 
# =====================================================================================================

class OwnerSignUpForm(UserCreationForm):
	"""
	Form for django User auth table
	"""
	email = forms.EmailField(required=True, help_text="We'll use this email to contact you")

	class Meta:
		model = User
		fields = ['first_name','last_name','username','email','password1','password2']

cardManager/views.py
#import stripe
import urllib.request
import json
from django.utils.safestring import mark_safe
from io import BytesIO
import requests
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
from datetime import datetime
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth import  login, views as auth_views
from django.http import HttpResponse
from django.http.response import JsonResponse
# from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic import UpdateView, CreateView, ListView, DetailView, RedirectView, TemplateView
from django.views.generic.base import ContextMixin, View
from django.template import loader
from django.db.models import Count, Q
from django.db.models.functions import TruncDay
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict
from django.contrib.auth.models import User
from cardManager.utils import gen_card_token
from cardManager.models import (
    Card,
    Profile,
    Usage,
    Design,
    Request
)
from .forms import (
    CardForm,
    AdminCardForm,
    ProfileForm,
    RequestForm,
    OwnerSignUpForm,
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Home Page fbv
class HomePage(ListView):
    model = Design
    template_name = 'cardManager/home.html'
    
def order_create(request):
    if request.method == "POST":
        form = RequestForm(request.POST, request.FILES)
        if request.user.is_authenticated and form.is_valid():
            #https://stackoverflow.com/questions/77784821/how-to-add-value-into-a-form-before-saving-in-django
            order_instance = form.save(commit=False)
            order_instance.owner = request.user
            form.save()
            if 'order_post' in request.session:
                del request.session['order_post']
            return redirect('dashboard_view')
        elif not request.user.is_authenticated and form.is_valid():
            request.session['order_post'] = request.POST
            url = reverse('signup_view')
            return redirect(f"{url}?next={request.path}")
    elif request.method == "GET":

        if 'order_post' in request.session:
            form = RequestForm(request.session.get('order_post'))
        else: 
            form = RequestForm()
        return render(request, 'cardManager/home.html', {'form':form, 'design_list': Design.objects.all()})

    
# Create and Saves Usage instance, given card field
def __add_to_usage(request, card):
    print('\ninit\'d __add_to_usage')
    new_use = Usage(card=card)
    new_use.save()


# Handles redirects for a scanned card matching card_token 
def card_detail(request,card_token):
    """
    Redirects the browser based on this card instance's attributes. 
    """
    card_exists = Card.objects.filter(token=card_token).exists()
    if card_exists:
        card = Card.objects.get(token=card_token)
        is_owned = not (card.owner == None)
        is_redirecting = not (card.reroute_url == "")

        if is_owned:
            __add_to_usage(request, card) 
            
        if is_owned and not card.show_profile and is_redirecting:
            return redirect(card.reroute_url)
        elif is_owned and card.show_profile:
            return redirect('profile_view', profile_slug=card.owner.profile.profile_slug)
        elif is_owned and not is_redirecting:
            return redirect('card_update_view',card_token=card_token)
        elif not is_owned:
            return redirect('card_activate_view', card_token=card_token) 
    elif not card_exists and request.user.is_authenticated and request.user.is_superuser:
        return redirect('card_create_view', card_token=card_token)
    else:
        return render(request, 'cardManager/404.html')



class CardActivate(DetailView, LoginRequiredMixin):
    """
    Renders Card instance to card activate HTML template. 
    """
    model = Card
    slug_field = 'token'
    slug_url_kwarg = 'card_token'
    template_name = 'cardManager/activate.html'

    def get(self,request, **kwargs):
        # Retrieve card instance with given card_token
        card = self.get_object()
        if card.owner:
            # Reroute to card "scanning" view
            return redirect('card_view', card_token=card.token)
        return super().get(self, request, **kwargs)

    def post(self, request, **kwargs):
        card = self.get_object()
        if request.user.is_authenticated:
            # Set this card owners user
            card.owner = request.user
            card.save()
            return redirect('card_update_view', card_token=card.token)
        else:
            #Pass next parameter to signup view
            request.session['activating_card_design'] = card.design.front_design.url
            url = reverse('signup_view')
            activate_url = reverse('card_activate_view', kwargs={'card_token': card.token})
            return redirect(f'{url}?next={activate_url}')

        return super().post(self, request, **kwargs)


class CardCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Card
    form_class = AdminCardForm
    slug_field = 'token'
    slug_field = 'card_token'
    template_name = 'cardManager/card_create.html'
    permission_required = 'auth.add_user'
    success_url = reverse_lazy('dashboard_view')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_token'] = self.kwargs.get('card_token')
        print(context)
        return context


# A11: Updating a card requires a user to be logged in
class CardUpdate(LoginRequiredMixin,UpdateView):
    model = Card
    form_class = CardForm
    slug_field = 'token'
    slug_url_kwarg = 'card_token'
    template_name = 'cardManager/card_update.html'
    success_url = reverse_lazy('dashboard_view')


# A11: Updating a card requires a user to be logged in
@login_required(login_url='login_view')
def card_update(request, card_token):
    """
        FBV for handling card update functionality
    """
    card = get_object_or_404(Card, token=card_token)
    initial_alias = card.alias
    if request.method == "GET":
        # Populate form with data from card model instance
        form = CardForm(instance=card)
        hide_redirect_div = card.show_profile
    elif request.method == "POST":
        # Let's update the current card instance with data from forms       
        form = CardForm(request.POST, instance=card)
        owner_has_profile =  Profile.objects.filter(owner_id=card.owner.pk).exists()
        hide_redirect_div = (card.show_profile or request.POST.get('show_profile')) and "route" not in str(form.errors)
        if form.is_valid():
            submitted_alias = form.cleaned_data['alias']
            """
             A8: form.save() was being called when the alias wasn't unique
             I'll handle the error gracefully by throwing an error when: 
                - The inital alias differs from the submitted alias
                - AND when the submitted alias and card.owner combo exists already  
            
            """
            alias_has_changed = not submitted_alias == initial_alias
            alias_in_use = ( Card.objects.filter(alias=submitted_alias, owner=card.owner).exists() )
            if alias_in_use and alias_has_changed:
                form.add_error("alias", "A card already has this name")
            else:
                
                if owner_has_profile and request.POST.get('show_profile'):
                    form.save()
                    return redirect('dashboard_view')
                else:
                    return redirect('profile_create_view')
            

    
    return render(request, 'cardManager/card_update.html', {'form': form, 'card': card, 'hide_redirect_div': hide_redirect_div})

class ProfileCreate(LoginRequiredMixin, CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'cardManager/profile_create.html'


# Render profile template using the slugs instead of pk
class ProfileDetail(DetailView):
    model = Profile
    template_name = 'cardManager/profile.html'
    slug_field = 'profile_slug'
    slug_url_kwarg = 'profile_slug'

class ProfileUpdate(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'cardManager/profile_update.html'
    slug_field = 'profile_slug'
    slug_url_kwarg = 'profile_slug'

# Renders dashboard template with owner cards
class UserDashboard(LoginRequiredMixin, ContextMixin, View):
    template_name = 'cardManager/dashboard.html'

    def get(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)

    # I need to alter the context that goes to the dashboard template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner_id = self.request.user.pk
        owner_cards = Card.objects.filter(owner_id=owner_id)
        owner_requested_cards = Request.objects.exclude(status="shipped").filter(owner_id=owner_id)
        recent_activities = Usage.objects.filter(card__owner=owner_id).order_by('-date_used')[0:5]
        context['user_cards'] = owner_cards
        context['recent_activities'] = recent_activities
        context['requested_cards'] = owner_requested_cards
        #A9: Setting up pending orders data  
        if self.request.user.is_authenticated:
            context['pending_orders'] = Request.objects.all()
        return context


class Stats(LoginRequiredMixin, ListView):
    model = Usage
    template_name = 'cardManager/stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

cardManager/templates/cardManager/activate.html
{% extends 'cardManager/base.html' %}
{% load static  %}
{% block title %}
	Activating your Card | TC Digital
{% endblock %}
{% block opener %}
Activating card {{ card.token }}
{% endblock opener %}
{% block hero_header %}
    <div class="card flex items-center justify-center rounded-md ">
        <img id="card" class=" object-cover w-[15rem] rounded-md aspect-[8/5]" src="{{ card.design.front_design.url }}"/>
    </div>
{% endblock %}

{% block hero_text %}
    Activating Card {{ card.token }}
{% endblock %}
{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<button type="submit" id="activateCardBtn" class="bg-[var(--color-main)] w-full text-center py-4 rounded-md mt-8">Claim this card</button>
		
	</form>
{% endblock %}
{% block extra_scripts %}
{% endblock %}

cardManager/templates/cardManager/card_create.html
    {% extends 'cardManager/base.html' %}
    {% load static %}
    {% block title %}
    Registering your Card | TC Digital
    {% endblock %}
    {% block opener %}
    Registering card
    {% endblock opener %}
    {% block hero_header %}
    <div class="card flex items-center justify-center rounded-md ">
        <img id="card" class=" object-cover w-[15rem] rounded-md aspect-[8/5]" src="{{ card.design.front_design.url }}" />
    </div>
    {% endblock %}
    {% block hero_text %}
    Registering Card {{ card.token }}
    {% endblock %}
    {% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>Token</p>
        <input type="text" name="token" id="id_token" value="{{ new_token }}">
        <input class="hidden" type="text" value="" name="owner">
        <div class="">
        	{{ form.design }}
        </div>
    	<button type="submit" class="bg-[var(--color-main)] w-full text-center py-4 rounded-md mt-8">Register Card</button>
    </form>
    {% endblock %}
    {% block extra_scripts %}
    {% endblock %}

cardManager/templates/cardManager/card_update.html
{% extends 'cardManager/base.html' %}
{% load static %}
{% block opener %}
Updating Card
{% endblock %}

{% block hero_text %} 
	{% if card.alias %}
		Update {{ card.alias }}
	{% else %}
		Update your Card
	{% endif %}
{% endblock %}
{% block hero_header %}
<div class="flex flex-row justify-center gap-2 mb-10">
	<img 
		class="w-[16rem] h-[10rem] rounded-sm md:w-[20rem] md:h-[13rem]"
		src="{{ card.design.front_design.url }}"
	/>
</div>
{% endblock %}
{% block content %}
	<form method="post" class="flex flex-col gap-7">
		{% csrf_token %}
		<div class="flex flex-col gap-1">
	    	<label for="id_alias" class="text-bold text-lg">Card Name</label>
	    	<input 
		    	type="text" 
		    	class="bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md p-4" 
		    	placeholder="ex: Main Card" 
		    	id="id_alias" 
		    	name="alias" 
		    	maxlength="{{ form.fields.alias.max_length }}" 
		    	{% if card.alias %} value="{{ card.alias }}" {% endif %}
		    	{% if form.alias.errors %} style="border-color:var(--color-danger)" {% endif %}
		    	required
	    	/>
	    	{% if form.alias.errors %}
	    		<p class="text-danger text-sm" >{{ form.alias.errors }}</p>
	    	{% endif %}
    	</div>
    	<div class="flex flex-col gap-1">
	    	<label for="id_show_profile" class="text-bold text-lg">Show Profile on Tap</label>
	    	<div class="flex flex-row gap-3">
		    	<input 
		    		type="radio"
		    		onclick="toggleRedirectDiv(this.id)" 
			    	class="bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md" 
			    	value="True" 
			    	id="yes" 
			    	name="show_profile" 
			    	{% if hide_redirect_div  or form.cleaned_data.show_profile %} checked {% endif %}
			    >
		    	<input type="radio" onclick="toggleRedirectDiv(this.id)" class="bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md"  value="False" id="no" name="show_profile" {% if not hide_redirect_div and not form.cleaned_data.show_profile %} checked {% endif %}>
	    	</div>
    	</div>
    	<div class="flex flex-col gap-1 dimmable {% if hide_redirect_div %} dim-out {% endif %}" id="redirectDiv">
	    	<label for="id_reroute_url" class="text-bold text-lg">External Link</label>
	    	<input 
		    	type="url" 
		    	class="bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md p-4" 
		    	placeholder="ex: https://instagram.com" 
		    	id="id_reroute_url" 
		    	name="reroute_url"
		    	maxlength="{{ form.fields.reroute_url.max_length }}"
		    	{% if form.data.reroute_url %} value="{{ form.data.reroute_url }}"
		    	{% elif card.reroute_url %} value="{{ card.reroute_url }}" {% endif %}
		    	{% if form.reroute_url.errors %} style="border-color:var(--color-danger)" {% endif %}
	    	/>
	    	{% if form.reroute_url.errors %}
	    		<p class="text-danger text-sm" >{{ form.reroute_url.errors }}</p>
	    	{% endif %}
    	</div>
		<input class="bg-[var(--color-main)] rounded-md py-4 mt-9" type="submit" value="Save Changes">
	</form>
{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/forms.js' %}?v={{ tz }}"></script>
{% endblock %}

cardManager/templates/cardManager/home.html
{% extends 'cardManager/base.html' %}
{% load static  %}
{% block title %}
	TC Digital | Digital Cards 
{% endblock %}
{% block hero_text %} The only business card you'll need  {% endblock %}
{% block content %}
    <section id="features" class="mb-40 hidden">
        <h2 class="text-2xl mb-10">
            Features
        </h2>
        <div class="w-full flex flex-row overflow-x-auto gap-4">
           <div class="feature w-60 bg-white rounded-md  lg:w-30">
            <div class="icon-and-head flex flex-row"></div>
            <img src="" alt="">
            <h2 class="text-xl text-black">Infinite Taps</h2>
            <div>
                <p class="text-md text-grey"></p>
            </div>
           </div>
           <div class="feature w-60 bg-white rounded-md  lg:w-30">
            <div class="icon-and-head flex flex-row"></div>
            <img src="" alt="">
            <h2 class="text-xl text-black">QR Included</h2>
            <div>
                <p class="text-md text-grey"></p>
            </div>
           </div>
           <div class="feature w-60 bg-white rounded-md  lg:w-30">
            <div class="icon-and-head flex flex-row"></div>
            <img src="" alt="">
            <h2 class="text-xl text-black">Taps</h2>
            <div>
                <p class="text-md text-grey"></p>
            </div>
           </div>
        </div>
    </section>
    <section id="design" class="flex flex-col items-center mb-12 w-full m-auto gap-12">
        
        <div class=" flex w-max items-center justify-center relative">
            <img id="card" class="object-cover rounded-md h-[11rem] w-[18rem]" src="{{ design_list.first.front_design.url}}"/>
            <div class="w-full h-full absolute top-0 left-0" style="background:var(--color-reflective)"></div>
        </div>
        <h2 class="mb-5 hidden">
            Choose a Preset Design
        </h2>
        <div class="w-full overflow-x-auto md:flex md:justify-center md:items-center ">
            <div class="flex flex-row md:grid md:grid-cols-[1fr_1fr_1fr_1fr] gap-2 md:gap-4 w-max">
                {% for design in design_list %}
                    {% if design.front_design.url %}
                        <button onclick="setDesignChoice(this)" >
                            <img src="{{ design.front_design.url }}" data-id="{{ design.pk }}" class="w-[6rem] h-[3.5rem] object-cover rounded-md" />
                        </button>
                    {% endif %}
                {% endfor %}
                <button onclick="showUploadFile()" >
                    <p class="w-[6rem] h-[3.5rem] object-cover rounded-md flex justify-center text-5xl" style="border: 2px dashed var(--color-input-border);">
                        <svg xmlns="http://www.w3.org/2000/svg" style="fill:var(--color-input-border);width:2rem;height:3rem" viewBox="0 0 640 640"><!--!Font Awesome Free v7.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M304 112L192 112C183.2 112 176 119.2 176 128L176 512C176 520.8 183.2 528 192 528L448 528C456.8 528 464 520.8 464 512L464 272L376 272C336.2 272 304 239.8 304 200L304 112zM444.1 224L352 131.9L352 200C352 213.3 362.7 224 376 224L444.1 224zM128 128C128 92.7 156.7 64 192 64L325.5 64C342.5 64 358.8 70.7 370.8 82.7L493.3 205.3C505.3 217.3 512 233.6 512 250.6L512 512C512 547.3 483.3 576 448 576L192 576C156.7 576 128 547.3 128 512L128 128zM387.4 496L252.6 496C236.8 496 224 483.2 224 467.4C224 461 226.1 454.9 230 449.8L297.6 362.9C303 356 311.3 352 320 352C328.7 352 337 356 342.4 362.9L410 449.9C413.9 454.9 416 461.1 416 467.5C416 483.3 403.2 496.1 387.4 496.1zM240 288C257.7 288 272 302.3 272 320C272 337.7 257.7 352 240 352C222.3 352 208 337.7 208 320C208 302.3 222.3 288 240 288z"/></svg>
                    </p>
                </button>
            </div>
        </div>
        <form action="{% url 'order_card_view' %}" class=" flex flex-col gap-12 w-3/4" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="uploadFile" class="flex flex-col gap-6 hidden">
                <h2 class="text-center mb-6">
                    Upload your own design
                </h2>
                <div class="w-full ">
                    {% if request.session.order_post %}
                        {{ form.custom_design }}
                    {% else %}
                    <input type="file" class="w-full bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md p-4" placeholder="Upload a file" id="id_custom_design" name="custom_design">
            
                    {% endif %}
                </div>
            </div>
            <div class="w-full  hidden">
                <h2 class="mb-5">
                    How many do you need?
                </h2>
                {% if request.session.order_post %}
                    {{ form.card_qty }}
                {% else %}
                <input type="number" value="1" class="bg-[var(--color-input-bkg)] border-solid border-[1px] border-[var(--color-input-border)] rounded-md p-4" min="1" max="500" id="id_card_qty" name="card_qty">
                {% endif %}
        
            </div>
            <input 
                type="hidden" 
                name="owner" 
                value="{% if request.user %} {{ request.user.pk }} {%endif%}"
            />
            <input 
                type="hidden" 
                name="preset_design" 
                id="design_choice" 
                {% if request.session.order_post %}
                value="{{ form.data.preset_design }}"
                {% else %}
                value="1"{% endif %}

            />
            <button class="bg-[var(--color-main)] w-full text-center py-4 rounded-md " id="order-btn" type="submit">
                Order Card
            </button>

        </form>
    </section>
    
{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/updateDesign.js' %}?v={{ tz }}"></script>

{% if request.session.order_post and request.user.is_authenticated %}
    <script type="text/javascript">
        let design_id = document.querySelector('#design_choice').value;
        preselectDesignChoice(design_id)
    </script>
{% endif %}
{% endblock %}